name: reader_ebooks
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-149.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  vocsy_epub_viewer: ^2.0.0
  http: ^1.1.0
  dio: ^5.3.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
